[package]
name = "repo-quest-gui"
version = "0.1.10"
edition = "2024"
default-run = "repo-quest-gui"
publish = false

[build-dependencies]
tauri-build = { version = "2.1.1", features = ["config-toml"] }

[dependencies]
tauri = { version = "2.4.1", features = ["config-toml", "devtools"] }
tauri-plugin-dialog = "2.2.1"
tauri-plugin-shell = "2.2.1"
tokio = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta = { workspace = true }
specta-typescript = "0.0.7"
tauri-specta = { version = "=2.0.0-rc.20", features = ["derive", "typescript"] }
rq-core = { path = "../rq-core" }
eyre = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
