volumes:
  repoquest-forgejo:
  repoquest-bot:
services:
  forgejo:
    image: repoquest-forgejo
    build:
      dockerfile: Dockerfile.forgejo
    healthcheck:
      test: '[ -f "$(dirname "$${GITEA_APP_INI}")"/configured ] && curl -s http://localhost:3000/healthz'
      start_period: 10s
      start_interval: 2s
    environment:
      - RQ_PORT
      - RQ_SSH_PORT
    ports:
      - "${RQ_SSH_PORT:-2222}:2222"
    volumes:
      - type: volume
        source: repoquest-forgejo
        target: /var/lib/gitea
  forgejo-runner:
    image: repoquest-forgejo-runner
    build:
      dockerfile: Dockerfile.forgejo-runner
    depends_on:
      forgejo:
        condition: service_healthy
    # Let forgejo-runner attempt to kill containers it started before killing
    # it.
    stop_grace_period: 30s
    volumes:
      - type: bind
        source: "${RQ_DOCKER_HOST:-/var/run/docker.sock}"
        target: /var/run/docker.sock
  repoquest:
    image: repoquest
    build:
      dockerfile: Dockerfile.repoquest
    depends_on:
      forgejo:
        condition: service_healthy
    environment:
      - RUST_LOG
      - RQ_PORT
    volumes:
      - type: volume
        source: repoquest-bot
        target: /srv/repoquest
  reverse-proxy:
    image: repoquest-reverse-proxy
    build:
       dockerfile: Dockerfile.reverse-proxy
    ports:
      - "${RQ_PORT:-8085}:8085"
    depends_on:
      - forgejo
      - repoquest
