FROM rust:alpine AS rq-bot-build

RUN apk add --no-cache \
    openssl-dev \
    openssl-libs-static \
    musl-dev
ADD ./ /root/app
RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/root/app/target/ \
    cd /root/app && \
    cargo build --release && \
    cp target/release/repo-quest-bot /root/app/repo-quest-bot

FROM alpine:latest

RUN apk add \
    dumb-init \
    openssl \
    curl \
    git \
    tar \
    gzip

COPY --from=rq-bot-build /root/app/repo-quest-bot /usr/local/bin/repo-quest-bot
ADD --chmod=755 run-repoquest.sh /usr/local/bin/run-repoquest.sh

RUN adduser -S -D -h /srv/repoquest repoquest
USER repoquest

RUN git config --global user.name "repoquest"
RUN git config --global user.email "repoquest@example.com"

ENTRYPOINT ["run-repoquest.sh"]
