server {
    listen 8085 default_server;
    listen [::]:8085 default_server;

    location /rq/ {
        proxy_pass  http://repoquest:8000/;
    }

    location / {
        proxy_pass  http://forgejo:3000/;
    }
}
