
product-name = "repo-quest"
version = "0.1.0"
identifier = "com.repo-quest.app"

[build]
before-build-command = "cd ../../js && depot -p repo-quest build --release"
before-dev-command = "cd ../../js && depot --no-fullscreen -p repo-quest build --watch"
dev-url = "http://localhost:5173"
frontend-dist = "../../../js/packages/repo-quest/dist"

[app]
windows = [{title = "RepoQuest", width = 1200, height = 800}]

[bundle]
active = true
targets = "all"
icon = [
  "icons/32x32.png",
  "icons/128x128.png",
  "icons/128x128@2x.png",
  "icons/icon.icns",
  "icons/icon.ico"
]