# Taken from:
# https://codeberg.org/forgejo/-/packages/container/forgejo
FROM codeberg.org/forgejo/forgejo:13-rootless

USER root
RUN apk add curl

ADD --chmod=755 ./docker/run-forgejo.sh /usr/local/bin/run-forgejo.sh

USER git

ADD --chmod=644 ./docker/app.ini /etc/templates/app.ini
ADD --chown=644:644 ./docker/custom/templates "/etc/templates/templates"
ADD --chown=644:644 ./docker/custom/public "/etc/templates/public"

ENV RQ_PORT=8085

ENTRYPOINT ["run-forgejo.sh"]
