server {
    listen 8085 default_server;
    listen [::]:8085 default_server;

    location /rq/ {
        proxy_pass  http://repoquest:8000/;

        # websocket support
        # note(wcrichto): once nginx updates, proxy_http_version will no longer be needed.
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location / {
        proxy_pass  http://forgejo:3000/;
    }
}
