[package]
name = "rq-cli"
version = "0.1.5"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
rq-core = { path = "../rq-core" }
tokio = { workspace = true, features = ["rt-multi-thread"] }
anyhow = { workspace = true }
serde_json = { workspace = true }