schema = "../gen/schemas/desktop-schema.json"
identifier=  "default"
description = "Capability for the main window"
windows = ["main"]
permissions = [
  "core:default",
  "dialog:allow-open",
  "shell:allow-open"
]