name: CI

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: Swatinem/rust-cache@v2

      - name: Tests
        run: cargo test

      - name: Lints
        run: cargo fmt --check && cargo clippy -- -D warnings