name: CI

on: [push]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./rs
      - name: Setup
        uses: ./.github/workflows/setup      
      - name: Backend tests
        run: |
          cargo test
          cargo clippy -- -D warnings
        working-directory: rs
      - name: Frontend tests
        run: |
          depot test
          depot --no-incremental build --lint-fail
        working-directory: js