name: Tests

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: cargo build --verbose
      - run: cargo test --verbose
      - run: cargo clippy --verbose
